name: workflow-devtest-complex
on:
  push:

jobs:
  setup-jdk:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
  unit-test:
    needs: setup-jdk
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
  architecture-test:
    needs: setup-jdk
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
  integration-test:
    needs: setup-jdk
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
  build-image:
    needs:
      - unit-test
      - architecture-test
      - integration-test
      - code-analysis
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
